### PR TITLE
Update vinyl and through2 deps

### PR DESCRIPTION
**Pull request by phated**
@hughsk can you get this merged and published right away?  A lot of people are having trouble with the new alpha of gulp 4 due to outdated vinyl deps.

### CODE REVIEW

**Comment by erikkemperman** [comment]
+1 fro me!

**Comment by phated** [comment]
@hughsk thanks for the invite. Can you also add me on npm?

**Comment by hughsk** [comment]
Done! :)

**Comment by phated** [comment]
Thanks! published

**Pull request merged**
